### ISSUE TITLE
Lỗi - Không chỉ định được CLS khi bệnh nhân BHYT có toa mua ngoài

### ISSUE THREAD

**Issue by lequocthong29** [dh-his/Ghi_Nhan_Loi#15]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐÔNG TÂY**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_chidinhcls_bndacaptoa_18102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ecHTunRYr)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022005990` - _**MaKB**_: `2410020561` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/10/2024` - _**MaPhong**_: `H16` - _**MaDV**_: `K02` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Bệnh nhân BHYT có toa mua ngoài (toa nhà thuốc) thì không chỉ định được CLS (Prescription báo bệnh nhân đã có toa thuốc)

![](https://i.imgur.com/vfpeLJJ.png)
![](https://i.imgur.com/v6LoYi9.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1106.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Prescription đã fix lỗi Không chỉ định được CLS khi bệnh nhân BHYT có toa mua ngoài

- Hình ảnh: 
Bệnh nhân cũ
![](https://i.imgur.com/mbjZRH5.png)
![](https://i.imgur.com/Yh8DmeS.png)

Bệnh nhân BHYT mới
![](https://i.imgur.com/GLMe4nF.png)
![](https://i.imgur.com/f6CZfd2.png)

Bệnh nhân trẻ em mới
![](https://i.imgur.com/7LkGGxw.png)
![](https://i.imgur.com/P5ALjL2.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
