### ISSUE TITLE
Lỗi - Xem kết quả xét nghiệm hiển thị nhiều lần (BV Phụ Sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-his/Ghi_Nhan_Loi#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_28102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
- 
###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024088322` - _**MaKB**_: `2410019350` - _**MaBA**_: `018696` _**NgayKCB**_: `27/10/2024 6:55:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `08` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `HB07`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng xem kết quả -> phần mềm hiển thị trang kết quả nhiều lần cùng 1 cls.
```
Trang kết quả hiển thị nhiều lần
![ảnh](https://github.com/user-attachments/assets/996e13d8-8602-4857-ab86-0ec2be8f9e18)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
## Labor mẫu kết quả dư dòng trống
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:
Mẫu kết quả dư dòng trống
![ảnh](https://github.com/user-attachments/assets/2eae837d-5ca4-4633-9da5-ea16a4090303)
***

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
Treatment xem kết quả vẫn hiển thị nhiều lần. anh @vuongdh kiểm tra Treatment lại giùm em luôn nhe anh!

**Comment by vinh-dh** [comment]
> Mẫu kết quả dư dòng trống
> ![ảnh](https://github.com/user-attachments/assets/2eae837d-5ca4-4633-9da5-ea16a4090303)

Đây không phải lỗi. Đó là yêu cầu của BV Phụ Sản tại thời điểm làm hợp đồng cho mẫu kết quả này.
![image](https://github.com/user-attachments/assets/e0aa3e34-3b6f-49a0-a8ae-4898a2a4e81f)

**Comment by vinh-dh** [comment]
> Treatment xem kết quả vẫn hiển thị nhiều lần. anh @vuongdh kiểm tra Treatment lại giùm em luôn nhe anh!
> ![ảnh](https://github.com/user-attachments/assets/5e51840c-a943-47b5-b55b-b2d6afdf65d1)

@vuongdh, @lequocthong29: GitPullLibraries để lấy thư viện mới về, build lại cho trường hợp này cho Reg, Pre và Treat nhé!

**Comment by vuongdh** [comment]
@vinh-dh OK

**Comment by onghaup** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1031.1 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32410311-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32410311-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32410311-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Xem kết quả xét nghiệm hiển thị nhiều lần (BV Phụ Sản)

![](https://i.imgur.com/ZCWftIM.png)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by onghaup** [comment]
### 📣📣📣 Prescription.exe v.3.24.1031.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410310-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410310-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410310-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Xem kết quả xét nghiệm hiển thị nhiều lần (BV Phụ Sản)

![](https://i.imgur.com/ZCWftIM.png)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by onghaup** [comment]
### 📣📣📣 Treatment.exe v.4.24.1031.1 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42410311-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42410311-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42410311-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Xem kết quả xét nghiệm hiển thị nhiều lần (BV Phụ Sản) #20

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
***
> ✅  Hình ảnh chứng mình cho việc kiểm tra này: Đã fix
![ảnh](https://github.com/user-attachments/assets/30ab6751-9c58-471b-b0f6-78f60ba67356)
![ảnh](https://github.com/user-attachments/assets/85437fd8-b19f-4f9b-acb6-70443442276f)

> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
