### ISSUE TITLE
Lỗi - XML5_4750 load thiếu thông tin thủ thuật (BV Quảng ngãi)

### ISSUE THREAD

**Issue by le-an-87** [dh-his/Ghi_Nhan_Loi#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quangngai_31102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020008159` - _**MaKB**_: `2410005595` - _**MaBA**_: `2024001746` _**NgayKCB**_: `28/10/2024 4:30:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `16` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân ngày 22/10/2024 có chỉ định 2 cls DI122 và SA03 đã lập phiếu thủ thuật
-> XML5 chỉ load được thông tin 1 phiếu thủ thuật.

```
![ảnh](https://github.com/user-attachments/assets/15c77408-9384-4c7b-a87c-19b71bb455c3)
![ảnh](https://github.com/user-attachments/assets/f4cd20b9-c583-4dc2-a026-5d24b0d81262)
![ảnh](https://github.com/user-attachments/assets/b924a85c-1728-4fd2-aa17-da4944282113)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-11-19

**Comment by vuongdh** [comment]
Hậu: Lỗi này do XML5 lấy lên thiếu

**Comment by vuongdh** [comment]
Kiểm tra thấy có gì khác biệt ngoài phân loại phẫu thuật

![image](https://github.com/user-attachments/assets/d6368ef2-d2f7-4e3c-8a8a-422c3df22e6d)

![image](https://github.com/user-attachments/assets/413996b6-8085-42a7-91bf-adf1efb2d852)
