### ISSUE TITLE
Lỗi - Cập nhật tháng ra viện Chức năng kiểm tra tháng ra viện nội trú

### ISSUE THREAD

**Issue by le-an-87** [dh-his/Ghi_Nhan_Loi#32]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_01112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024020107` - _**MaKB**_: `2410013489` - _**MaBA**_: `2024008549` _**NgayKCB**_: `31/10/2024 8:00:00 CH` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `15` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng cập nhật tháng ra viện báo lỗi
```
![ảnh](https://github.com/user-attachments/assets/16a50431-9511-499f-b08b-e8664cf087e3)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_**

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1121.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411210-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411210-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411210-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Cập nhật tháng ra viện Chức năng kiểm tra tháng ra viện nội trú ![](https://i.imgur.com/Kmmm0UQ.png)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/32
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![jb3RbjQ7uP](https://github.com/user-attachments/assets/da31666b-354c-46a6-ac2a-1de0828f9539)
***
