### ISSUE TITLE
Lỗi - Thành tiền Mẫu 3360 theo đơn giá không có tỷ lệ chưa đúng

### ISSUE THREAD

**Issue by lqbinh1987** [dh-his/Ghi_Nhan_Loi#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquandanydt_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024034451; 2024034450` - _**MaKB**_: `2410011500; 2410011499` - _**MaBA**_: `MaBA` _**NgayKCB**_: `04/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Xem lại dùm em lỗi chổ theo [issue này](https://github.com/dh-his/Phieu_Yeu_Cau/issues/8) của Tuấn báo về mẫu 3360 xuất theo đơn giá không tỷ lệ.
Mẫu khi xuất Report 130 theo 285 đơn giá không có tỉ lệ hiện tại **CHƯA ĐÚNG**
![image](https://github.com/user-attachments/assets/aca81f29-f178-420b-91bb-c0721aaff218)

Mẫu 21 Tổng hợp hiện tại Xuất Excel 917 ĐƠN GIÁ KHÔNG THEO TỈ LỆ  **ĐANG ĐÚNG** như hình dưới
![image](https://github.com/user-attachments/assets/1954a793-5201-47d1-b4e9-6f91d6ced216)

Lưu ý là mẫu excel **Đơn giá có tỷ lệ** cũng bị tương tự

**Comment by vinh-dh** [comment]
☑️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-08.

**Comment by vinh-dh** [comment]
![image](https://github.com/user-attachments/assets/c314de50-02c5-480b-be21-a92fc5548341)
![image](https://github.com/user-attachments/assets/6ddb9028-13cc-4360-9ff2-bf8d9694c937)

@hvtuan1987, @lqbinh1987: theo 2 hình em cung cấp thì anh thấy cột `don_gia` đang đúng mà. Đâu có sai.

**Comment by lqbinh1987** [comment]
Thành tiền á anh @vinh-dh.

**Comment by onghaup** [comment]
### 📣📣📣 Reports.exe v.3.24.1105.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411050-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411050-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411050-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Sửa lỗi: Xuất Excel mẫu 21 (CV285) tại form xuất dữ liệu XML4750 bị sai đơn giá, tỷ lệ và thành tiền.

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/34
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi
![image](https://github.com/user-attachments/assets/795c90db-5030-498b-95af-c09288af444d)
