### ISSUE TITLE
Lỗi - Sai MA_DOITUONG_KCB khi bệnh nhân có thẻ Quân đội, Công an trong tỉnh nhưng có 2 ký tự mã tỉnh trong thẻ và 2 ký tự đầu mã nơi đăng ký KCB ban đầu khác với 2 ký tự đầu của mã cơ sở KCB

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#37]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51219`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA MINH QUANG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_minhquang_madoituongkcb_theqdca_04112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/mWwKJHkGY)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Admin, Printer, Prescription, Reports, Treatment`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024025737` - _**MaKB**_: `2411000779` - _**MaBA**_: `MaBA` _**NgayKCB**_: `4/11/2024` - _**MaPhong**_: `KB2` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có mã thẻ BH của Quân đội, Công an cùng tỉnh với cơ sở KCB nhưng mã tỉnh cấp thẻ và 2 ký tự đầu của nơi đăng ký KCB ban đầu khác với 2 ký tự đầu mã cơ sở đăng ký KCB thì phần mềm Admin và các phần mềm xuất XML khác xuất MA_DOITUONG_KCB = 9

Ví dụ trường hợp bệnh nhân có mã thẻ CA5 98 9813362509 - 98451 Bệnh xá Công an tỉnh Quảng Ngãi thuộc tỉnh Quảng Ngãi mã tỉnh 51. khi đến phòng khám ĐK Minh Quang - 51219 KCB thì XML 4750 xuất MA_DOITUONG_KCB = 9. Thẻ trong tỉnh thuộc tuyến huyện theo đúng thì trường hợp này là thông tuyến
-> Fix lỗi hoặc bổ sung trường hợp này

![](https://i.imgur.com/rb3Ag9r.png)
![](https://i.imgur.com/O4M80h3.png)
![](https://i.imgur.com/6jALtmj.png)
![](https://i.imgur.com/cX10asx.png)
![](https://i.imgur.com/739Nbgt.png)

**Comment by vinh-dh** [comment]
☑️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-18.

**Comment by vinh-dh** [comment]
@lequocthong29 em kiểm tra lại trường hợp này nhé! Anh phát hiện nguyên nhân là do tại form đăng ký khám bệnh/form hiệu chỉnh thông tin bệnh nhân chưa theo mô tả, nên dữ liệu lưu trữ bị sai. Cụ thể:

- Theo [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md):
![image](https://github.com/user-attachments/assets/b563b291-3c4a-4525-9c10-2b00a65e3f1a)
- Bệnh viện hiện tại có tham số `tuyenbv = 2` và `thetrongtinh = 1`. Nhưng giá trị `psdangky.tuyenxml = 0`. Nếu đúng mô tả trường hợp này thì `psdangky.tuyenxml = 1`
![image](https://github.com/user-attachments/assets/7878bf56-d7be-4da5-93cf-3d5b80f11d8d)
**==> Kéo theo là xuất XML mã đối tượng bị sai.**

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-11-18.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1118.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411180-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411180-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411180-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - psdangky.tuyenxml lưu chưa đúng mô tả.

- Trường hợp `tuyenbv <= 2` ⇒ Người bệnh ngoài tỉnh: Nếu `psdangky.giayxacnhancutru = 1` thì `[psdangky.tuyen = 0 và psdangky.tuyenxml = 0]`, ngược lại `[psdangky.tuyen = 0 và psdangky.tuyenxml = 1]`.

![](https://i.imgur.com/DbX0EBP.png)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/37
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1118.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411181-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411181-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411181-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - psdangky.tuyenxml lưu chưa đúng mô tả.

- Trường hợp `tuyenbv <= 2` ⇒ Người bệnh ngoài tỉnh: Nếu `psdangky.giayxacnhancutru = 1` thì `[psdangky.tuyen = 0 và psdangky.tuyenxml = 0]`, ngược lại `[psdangky.tuyen = 0 và psdangky.tuyenxml = 1]`.

![](https://i.imgur.com/DbX0EBP.png)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/37
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 
Trường họp này có thể không phải sai tuyenxml nha anh. tuyenxml = 0 là đúng do mã BV 98451 là cơ sở cùng tỉnh với mã cơ sở 51219 thuộc tuyến huyện -> thông tuyến MA_DOITUONG_KCB = 1.2
Nếu chỉnh tuyenxml = 1 thì MA_DOITUONG_KCB = 3.3 (trái tuyến hưởng cùng tuyến)

- Ảnh chỉnh tuyenxml =1
![](https://i.imgur.com/Od4RiCQ.png)
![](https://i.imgur.com/VL6FrNt.png)
![](https://i.imgur.com/yTXcVCw.png)

**Comment by vinh-dh** [comment]
@chauthanhtra sai chứ không sai gì?
```
- psdangky.mabvdk = 98451
- psdangky.mabvkb = 51219
- Tham số thetrongtinh = 1
- Tham số tuyenbv = 2
```

Dựa vào các thông tin trên, theo mô tả:
![image](https://github.com/user-attachments/assets/b563b291-3c4a-4525-9c10-2b00a65e3f1a)

Thì dữ liệu đúng phải là:
```
- psdangky.tuyen = 0
- psdangky.tuyenxml = 1
```

Nhưng dữ liệu gốc ban đầu `psdangky.tuyenxml = 0` ==> **SAI**

**Comment by chauthanhtra** [comment]
> @chauthanhtra sai chứ không sai gì?
> 
> ```
> - psdangky.mabvdk = 98451
> - psdangky.mabvkb = 51219
> - psdangky.giayxacnhancutru = 0
> - Tham số thetrongtinh = 1
> - Tham số tuyenbv = 2
> ```
> 
> Dựa vào các thông tin trên, theo mô tả: ![image](https://private-user-images.githubusercontent.com/112069710/386521139-b563b291-3c4a-4525-9c10-2b00a65e3f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTU3NTAsIm5iZiI6MTczMTkxNTQ1MCwicGF0aCI6Ii8xMTIwNjk3MTAvMzg2NTIxMTM5LWI1NjNiMjkxLTNjNGEtNDUyNS05YzEwLTJiMDBhNjVlM2YxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDA4NmVmZTlmODYwNDg1MmVlYWM3OGUwYjYzYTQwNjNiNDNiODkxMjU1MjYwNTk5NGNmMTQzYzI1OGRhMjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vizx7NCnTiUlZgVcxN-yxpSsxX7L9DWq3axeEIIlYTI)
> 
> Thì dữ liệu đúng phải là:
> 
> ```
> - psdangky.tuyen = 0
> - psdangky.tuyenxml = 1
> ```
> 
> Nhưng dữ liệu gốc ban đầu `psdangky.tuyenxml = 0` ==> **SAI**

- Ok anh. Theo mô tả này thì psdangky.tuyenxml = 0 là sai. Em hiểu sai chổ có check cùng tuyến trên danh mục BV, nó không có ảnh hưởng tuyenxml. psdangky.tuyenxml = 1 mới đúng mô tả này.

- Vậy trong trường hợp này thì làm sao để xuất được MA_DOITUONG_KCB = 1.2 ( thông tuyến ) vậy anh?

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalRegister.exe v.3.24.1118.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Nhận bệnh đã ghi nhận psdangky.tuyenxml theo mô tả

- Hình ảnh: 

![](https://i.imgur.com/vKcdrxg.png)
![](https://i.imgur.com/71RlYWm.png)
![](https://i.imgur.com/ySyabox.png)

**Comment by vinh-dh** [comment]
> Vậy trong trường hợp này thì làm sao để xuất được MA_DOITUONG_KCB = 1.2 ( thông tuyến ) vậy anh?

Xem mô tả [ma_doituong_kcb](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/ma_doituong_kcb.md) nè @chauthanhtra.

**Comment by chauthanhtra** [comment]
Anh @vinh-dh 
Theo mô tả này thì không đúng trong trường hợp thẻ quân đội công an
Do 2 ký tự trong mã nơi đăng ký ban đầu (98) và ký tự 4, 5 trong mã thẻ đều (98) không giống 2 ký tự đầu trong mã BV khám bệnh (51)
Nhưng thẻ này là của BV tuyến huyện cùng tỉnh với BV khám bệnh. là được hưởng thông tuyến

**Comment by vinh-dh** [comment]
Các lỗi của git này @lequocthong29 đã fix. Còn yêu cầu mới như em nói: xác định thẻ trong tỉnh dựa vào mã tỉnh của bệnh viện (cấp thẻ) thì em lập y/c mới đi.

**Comment by chauthanhtra** [comment]
Đóng chuyển qua yêu cầu mới
