### ISSUE TITLE
Lỗi - Reports : Mẫu 25aCT và 25aTH thống kê dữ liệu bệnh nhân chưa in phiếu (psdangky.dain = 0)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_mau25_khonglaythuoc_29102024_1`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/zhbmBexaH)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011790` - _**MaKB**_: `2409004199` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/9/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân xác nhận không lấy thuốc không in bảng kê thì psdangky.dain = 0 , các bảng khác như khambenh, chidinhcls, chungtu có dain =2
- Mẫu 25aCT và 25aTH thống kê dữ liệu bệnh nhân này lên báo cáo -> gây ra lệch với các báo cáo khác (các mẫu khác không thống kê bệnh nhân này)

![](https://i.imgur.com/dZzT3ap.png)
![](https://i.imgur.com/BX66CMC.png)
![](https://i.imgur.com/1iN2JaV.png)
![](https://i.imgur.com/xJ0jWLS.png)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm tra nguyên nhân và chỉnh lỗi nếu có._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vinh-dh** [comment]
☑️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-18.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Reports.exe v.3.24.1117.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411170-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411170-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411170-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Sửa lỗi: Mẫu 25aCT và 25aTH thống kê dữ liệu bệnh nhân chưa in phiếu (psdangky.dain = 0).

![image](https://github.com/user-attachments/assets/14c5f137-3977-4286-9d0c-253122d81ac0)

![image](https://github.com/user-attachments/assets/3c488305-7d55-4f79-b430-02883416c74b)

![image](https://github.com/user-attachments/assets/3f2f70d2-eb25-41f5-b431-210626217cf0)

![image](https://github.com/user-attachments/assets/70fee2f1-f593-4087-adfc-249bd00fd179)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/40
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Reports.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Reports.exe v.3.24.1117.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Reports mới đã fix lỗi Mẫu 25aCT và 25aTH thống kê dữ liệu bệnh nhân chưa in phiếu (psdangky.dain = 0)

- Hình ảnh: 

![](https://i.imgur.com/1TeWsMH.png)
![](https://i.imgur.com/RZ6Cyqm.png)
![](https://i.imgur.com/ih0vI9I.png)
![](https://i.imgur.com/9rvDnqT.png)
![](https://i.imgur.com/OYig8HN.png)
![](https://i.imgur.com/e57yHpC.png)
![](https://i.imgur.com/Bskg02f.png)
![](https://i.imgur.com/HgHylFt.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
