### ISSUE TITLE
Lỗi - Prescription: BV Phụ Sản Toa vật tư kèm theo không lấy được thuốc từ tủ trực nhà thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#41]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_toavtyt_tutrucnhathuoc_kthaythuoc_07112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/nnsxuQF7k)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024043467` - _**MaKB**_: `2411004273` - _**MaBA**_: `MaBA` _**NgayKCB**_: `7/11/2024` - _**MaPhong**_: `36` - _**MaDV**_: `15` - _**ThangKT**_: `11` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription -> Chỉ định CLS -> Vật tư kèm theo -> Chọn tủ trực nhà thuốc -> không lấy được danh sách thuốc tủ trực nhà thuốc

Toa VTYT kèm theo trên Prescription không lấy được thuốc từ tủ trực nhà thuốc

![](https://i.imgur.com/iYDPXld.png)

- Cấp toa thường lấy được thuốc tủ trực nhà thuốc

![](https://i.imgur.com/BSlXwpt.png)

- Cấp toa VTYT kèm theo không lấy được thuốc tủ trực nhà thuốc
![](https://i.imgur.com/iLl7nbH.png)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Kiểm tra nguyên nhân và chỉnh lỗi._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-11-18.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription 17/11/2024
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Sau khi chỉnh tham số thì thấy thông tin thuốc từ tủ trực nhưng không cấp thuốc được do phần mềm báo không đủ thuốc để cấp
- Hình ảnh lỗi:

![](https://i.imgur.com/yPlT8OE.png)
![](https://i.imgur.com/z07thww.png)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '28/11/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription 3.24.1121.3
***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Prescription còn lỗi không cấp được toa VTYT kèm theo
  - Không thấy thuốc tủ trực thường
  - Thuốc tủ trực nhà thuốc phần mềm báo không đủ thuốc cấp phát
- Hình ảnh lỗi:

  - ![](https://i.imgur.com/EUDhy0u.gif)


***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH 2**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1122.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411220-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411220-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411220-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: fix - Lỗi toa vật tư nhà thuốc báo không đủ thuốc dù tồn kho vẫn còn

![](https://i.imgur.com/MDNG17u.gif)

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/41
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 3**
***
Phần mềm Prescription.exe v.3.24.1125.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription mới đã cấp được toa VTYT từ tủ trực nhà thuốc

- Hình ảnh: 

![](https://i.imgur.com/y5oMjNH.gif)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Khi cấp toa VTYT lấy thuốc từ kho thì khi chọn thuốc lần đầu thì phần mềm đóng form chọn thuốc rồi mở lại bắt chọn lại thuốc 
  - Không thấy thuốc từ kho tủ trực BHYT bình thường -> không cấp được toa

- Hình ảnh lỗi:

![](https://i.imgur.com/ftsT4Mh.gif)

***

Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1128.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411281-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411281-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411281-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Prescription: BV Phụ Sản Toa vật tư kèm theo không lấy được thuốc từ tủ trực nhà thuốc

- ☑: https://github.com/dh-his/Ghi_Nhan_Loi/issues/41
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '6/12/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1128.5
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription đã fix lỗi 
    - Khi cấp toa VTYT lấy thuốc từ kho thì khi chọn thuốc lần đầu thì phần mềm đóng form chọn thuốc rồi mở lại bắt chọn lại thuốc
    - Không thấy thuốc từ kho tủ trực BHYT bình thường -> không cấp được toa
    - Đã cấp được toa VT tủ trực nhà thuốc

- Hình ảnh: 
![](https://i.imgur.com/QUE5Ow2.gif)
![](https://i.imgur.com/x5tOjjm.gif)


***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Hiện tại các dữ liệu của các đơn vị khác không có triển khai tủ trực nhà thuốc cũng dùng được toa tủ trực nhà thuốc
- Hình ảnh lỗi:
BV QDY CT
![](https://i.imgur.com/UTIKsUA.gif)

PK Minh Quang
![](https://i.imgur.com/sQmkjlP.gif)

***

Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
❔THẮC MẮC❔
Anh @nghivanbi 
Trường hợp các đơn vị không có triển khai tủ trực nhà thuốc thì có cho cấp toa tủ trực nhà thuốc không anh

**Comment by chauthanhtra** [comment]
Nếu cần chuyển qua git mới để thảo luận thì code đề nghị để chuyển

**Comment by chauthanhtra** [comment]
[Chuyển qua git khác ](https://github.com/dhhiswork/Loi/issues/78)
