### ISSUE TITLE
Lỗi - BV QDY ST: Phần mềm Treatment tự tắt khi thao tác

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#42]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **8/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_st_full_treat_tutat`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5435`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/e5ggYR5p8)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

[Ghi lại]
Phần mềm Treatment tự tắt khi người dùng đang thao tác chưa khắc phục được
![](https://i.imgur.com/wn1DOcU.png)

Git cũ (https://github.com/dh-hos/dhg.hosptaltreatment/issues/137)
Phần mềm tự động tắt khi thao tác trên phần mềm như mở trang in hay kết thúc bệnh án, thường gặp nhất là khi kết thúc bệnh án
- Em có test thấy kết thúc vài bệnh thì phần mềm tự tắt

[`Clips quay thao tác của BV`] (https://gofile.me/78TQg/I4WZjCBjj)

Link youtube: (https://youtu.be/tnJ-96EmWKg)

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-11-13

**Comment by vuongdh** [comment]
@chauthanhtra em có test lại xem có bị không?

**Comment by chauthanhtra** [comment]
Lúc trước có test trên máy cá nhân chỉ biết phần mềm tự tắt nhưng không tìm được nguyên nhân nên mới nhờ anh kiểm tra trực tiếp cho BV .
BV báo còn lỗi này nên em ghi lại git này.
Anh cần test thì em sẽ test xem máy em có bị không nhưng chỉ biết nó tắt hay không thôi còn nguyên nhân thì không xác nhận được vì thao tác bình thường

**Comment by vuongdh** [comment]
Có nghĩa là kh em test vẫn bị tắt

**Comment by chauthanhtra** [comment]
Có bị tắt nhưng không cố định thao tác nào hay chức năng nào nên không quay lại được, lúc bị lúc không. lúc trước thường là khi kết thúc bệnh án hoặc mở trang in,... không cố đinh

**Comment by vuongdh** [comment]
OK em

**Comment by vuongdh** [comment]
Bữa hướng dẫn fix, ổn chưa @chauthanhtra

**Comment by chauthanhtra** [comment]
em đã test thử rồi nhưng vẫn còn bị tắt nha anh @vuongdh

**Comment by chauthanhtra** [comment]
chuyển qua git mới https://github.com/dhhiswork/Loi/issues/30
