### ISSUE TITLE
Lỗi - BV QDY CT: Printer in không lấy thuốc không hiện thông báo in phiếu, trạng thái dain có lúc = 2 (không hiện thông báo in phiếu), có lúc = 3 (có hiện thông báo có in phiếu không bấm bỏ qua), ...

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_mau25_khonglaythuoc_29102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tKRz5gE3c)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011791` - _**MaKB**_: `2410000001` - _**MaBA**_: `MaBA` _**NgayKCB**_: `7/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
   > _**MaBN**_: `2024011794` - _**MaKB**_: `2410000004` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
   > _**MaBN**_: `2024011795` - _**MaKB**_: `2410000005` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/11/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Printer 07/11/2024 hoặc cũ hơn
Khi in bệnh nhân Không lấy thuốc thì có 3 trường hợp:
1. Bấm Không lấy thuốc thì phần mềm không hiện thông báo hỏi chọn máy in có muốn in hay không, bấm Không lấy thuốc rồi là mất -> ghi nhận trạng thái khambenh.dain = 2
2. Bấm Không lấy thuốc thì phần mềm hiện thông báo hỏi chọn máy in có muốn in hay không, chọn Đóng không in phiếu -> ghi nhận trạng thái khambenh.dain = 3
3. Bấm Không lấy thuốc thì phần mềm hiện thông báo hỏi chọn máy in có muốn in hay không, chọn Đồng ý in phiếu -> ghi nhận trạng thái khambenh.dain = 2 , đồng thời psdangky.dain =1 và các thông tin khác
=> Đề nghị code kiểm tra thống nhất lại cách ghi nhận và có mô tả các trường họp này

- Clip trường hợp 1 và 2
https://gofile.me/78TQg/nl2tu1kEd

https://youtu.be/d3yyVv0C6JI

- Trường họp 3
![](https://i.imgur.com/inNl6wZ.png)
![](https://i.imgur.com/tRJ4fkK.png)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-23_**

**Comment by chauthanhtra** [comment]
Đã chuyển sang git mới https://github.com/dhhiswork/Loi/issues/33
