### ISSUE TITLE
Lỗi - Module: Register, Laboratory, Diagnose mở lên lâu - BV Đông Hải

### ISSUE THREAD

**Issue by minhduc2it** [dh-his/Ghi_Nhan_Loi#45]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Đông Hải**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_donghai_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/lRvf4ofhT

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Register: mở tab Đăng ký KCB rất lâu mới lên (kèm Video https://gofile.me/78TQg/Rn5YE3yTZ)

2. Laboratory, Diagnose khi mở lên rất lâu mới lên giao diện đăng nhập (Kèm Video https://gofile.me/78TQg/NY0aFqxv7)

Trao đổi với IT: Tất cả các máy đều bị chậm, test mở trực tiếp trên máy chủ vẫn chậm
Máy không cài Virut
Dữ liệu full lấy về kiểm tra thì mở bình thường không bị chậm.
_Dữ liệu và postgres đối với BV Đông Hải chỗ IT hơi nhạy cảm, nên em không can thiệp kiểm tra được. Nhờ bộ phận code hỗ trợ kiểm tra để tìm nguyên nhân_

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @onghaup 
-  📘 **Nội dung**:
- Rà soát lại xem có gì bất thường có thể hỗ trợ không nhé (check key qua internet...)

**Comment by onghaup** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi 
- **📘 Nội dung:** Xin remote đến máy chủ của khách hàng để kiểm tra

**Comment by minhduc2it** [comment]
⁉️** TRAO ĐỔI ** ⁉️
---
IT Báo các module trên mở lên bình thường, không bị chậm
![image](https://github.com/user-attachments/assets/746ea705-114c-4edf-8d7f-e2780a89eb57)
