### ISSUE TITLE
Lỗi - BV Ung Bướu: Fees Bảng kê bệnh nhân nợ viện phí  tính sai số tiền nợ khi bệnh nhân được miễn cùng tri trả

### ISSUE THREAD

**Issue by chauthanhtra** [dh-his/Ghi_Nhan_Loi#48]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92086`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ung Bướu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_ungbuou_nochiphi_12112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/3lQRR5j6Q)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023057368` - _**MaKB**_: `2410011776` - _**MaBA**_: `022056` _**NgayKCB**_: `12/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `05` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân có miễn cùng chi trả đã đóng hết số tiền cần trả nhưng phần mềm Fees báo bệnh nhân còn nợ chi phí. số tiền nợ là số tiền BH bệnh nhân được miễn cùng chi trả

![](https://i.imgur.com/EYplPjy.png)
![](https://i.imgur.com/WBvG7yJ.png)
![](https://i.imgur.com/EMa7jKN.png)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-19_**

**Comment by chauthanhtra** [comment]
Đã chuyển qua git mới https://github.com/dhhiswork/Loi/issues/17
