### ISSUE TITLE
Lỗi - BN BHYT load qua tiêu chí Không BHYT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-his/Ghi_Nhan_Loi#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_xml_kobhyt`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/q5s7QCeyt)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023014917` - _**MaKB**_: `2410002437` - _**MaBA**_: `N2024003042` _**NgayKCB**_: `24/10/2024` - _**MaPhong**_: `31` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN làm BANT theo đợt, có cho phí BHYT, nhưng lại nằm trong danh sách BN không BHYT

![image](https://github.com/user-attachments/assets/c8ee298c-0cb2-41ce-bf19-4af8e9f0c080)

Report đúng
![image](https://github.com/user-attachments/assets/1d685546-d1be-45c3-9d28-ca1dfa1f81a2)
![image](https://github.com/user-attachments/assets/a71994fc-89d7-40e9-81ce-11cb02f0adcf)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_**

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi

![image](https://github.com/user-attachments/assets/91db9f38-8b2e-42f5-bbf5-2a2c300c89e7)
![image](https://github.com/user-attachments/assets/680bddd3-bbce-4ea1-8347-8500b2dad384)
![image](https://github.com/user-attachments/assets/9dab0054-1031-4b84-9ac3-089067409cc0)
