### ISSUE TITLE
Lỗi - Admin hiển thị sai loại đối tượng 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-his/Ghi_Nhan_Loi#8]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84133`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tuan_dbsannhitv_xml_ngoaibhyt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_lechtongtien_bhyt`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/pjSVVFaz9)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021016165` - _**MaKB**_: `2410000166` - _**MaBA**_: `` _**NgayKCB**_: `01/10/2024` - _**MaPhong**_: `P02` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Admin hiển thị sai loại đối tượng khi xem XML 4750
Bệnh nhân BHYT nhưng lại nằm trong Không BHYT như hình dưới
Hình khi Xem tại Admin
![image](https://github.com/user-attachments/assets/936ce847-e18a-4bde-8e6e-cd4b52c7bba5)
Hình khi xem XML130 tại Report
![image](https://github.com/user-attachments/assets/1642794c-9faa-4712-bc05-d983f2b4ece8)

Hình hiển thị đúng khi xem XML  theo 4750 tại Report
![image](https://github.com/user-attachments/assets/4e8758ba-c22c-4735-a01c-ee9c651f548d)

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_**

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi
![image](https://github.com/user-attachments/assets/5a84eda3-ebf5-4182-b474-220378514bfc)
![image](https://github.com/user-attachments/assets/b3b9312f-589f-4ca3-9793-cad1e6768a67)
![image](https://github.com/user-attachments/assets/bfd3a842-53d5-47b1-a1ce-95749c612d1f)
Load XML cũng ok
![image](https://github.com/user-attachments/assets/9d7106bc-62a1-4749-a4b5-5ffe58ca9f9d)
