### ISSUE TITLE
Lỗi - Mất Menu Tool chỉnh định dạng font chữ khi sử dụng Mô tả bệnh lý (không chỉnh được định dạng kết luận và lời dặn)

### ISSUE THREAD

**Issue by vinh-dh** [dh-his/Ghi_Nhan_Loi#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_dinhdangpara_ketluan_dia_10102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/fgOiOJYcj)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012880` - _**MaKB**_: `2410003510` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/10/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `SI08` - _**PhieuYC**_: `PhieuYC`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi sử dụng tham số ha.sudungmotabenhly = 1 thì form bệnh lý và form chẩn đoán mất Menu Tool chỉnh định dạng font chữ. BV không chỉnh được định dạng font chữ cho lời dặn và kết luận  (bản in phiếu kết quả không chỉnh được định dạng chữ cho dữ liệu dạng RichText khi thiết kế mà phải chỉnh trong bệnh lý hoặc form trả kết quả)
-> Lấy lại menu tool định dạng font chữ

- Ảnh khi có menu tool chỉnh định dạng font khi tham số ha.sudungmotabenhly = 0 hoặc 2

![](https://i.imgur.com/N4lRERV.png)
![](https://i.imgur.com/uH48ulp.png)

- Ảnh khi không có menu tool chỉnh định dạng font khi tham số ha.sudungmotabenhly = 1

![](https://i.imgur.com/E0QHzEq.png)
![](https://i.imgur.com/2derVgi.png)
![](https://i.imgur.com/tHJG1dC.png)

### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.1014.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Form chẩn đoán đã có menu tool chỉnh định dạng font chữ và phiếu kết quả đã in được kết luận và lời dặn theo định dạng chữ đã chỉnh

- Hình ảnh: 

![](https://i.imgur.com/VYPHDsk.png)
![](https://i.imgur.com/93M25Ob.png)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Form bệnh lý chưa có menu tool chỉnh định dạng chữ cho kết luận và lời dặn mặc định ( Cần có chức năng này để BV chỉnh định dạng chữ mặc định không phải chỉnh từng bệnh nhân khi trả kết quả)
- Hình ảnh lỗi:
![](https://i.imgur.com/xjB1rKl.png)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.1031.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Diagnose đã chỉnh lại vị trí menu tool chỉnh định dạng chữ form bệnh lý khi tham số ha.sudungmotabenhly = 1

- Hình ảnh: 
![](https://i.imgur.com/O2Lcohg.png)
![](https://i.imgur.com/Y9HNkZF.png)
![](https://i.imgur.com/tOVVbEz.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
